### ISSUE TITLE
Request new feature

### ISSUE THREAD

**Issue by nikoHu** [llmhyy/mcidiff#1]
Dear author, 
        I'm very intrested in your code. I don't  know if this is a problem or not. When I run your test on three clone instance, eg.  "methodName throws Exception,   methodName,   methodName " or " methodName, methodName, methodName throws Exception", 
the code give the same result :  [throws Exception, e*, e*]，how can I get the order of the output diff Result.
I have three questions:
1, How to get the order of the output result?
2, How to get the token number of the result, eg. "throws" is the second token in "methodName throws Exception".
3, Is there an API provide full result like this: [methodName, methodName, methodName], [throws, e*, e*], [Exception, e*, e*].

**Comment by llmhyy** [comment]
Hi,

please refer to SeqMultiset.findTokenSeqByCloneInstance() to find the corresponding token under a clone instance.

**Comment by nikoHu** [comment]
Get it! Thanks very much!
